version: 2
jobs:
  build:
    working_directory: ~/Clever/clever-goals-js
    docker:
    - image: circleci/node:10.8.0-stretch
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run: npm install
    - run: make build
    - run: make test
    - run: npm prune --production
    # TODO: Automatically publish to assets
